name: Publish to CurseForge

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "liberica"
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build
          gradle-version: 8.1
      - name: Upload jar to CurseForge
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          name: ""
          version: ""
          files-primary: legacy/_1.7.10/build/libs/OKM-*.jar
          files-secondary: ""
          loaders: fabric
          game-versions: |
            1.7.10
          dependencies: |
            legacy-fabric-api
            fabric-language-kotlin
          java: 8
          curseforge-id: 626666
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
      - name: Upload jar to CurseForge
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          name: ""
          version: ""
          files-primary: legacy/_1.8.9/build/libs/OKM-*.jar
          files-secondary: ""
          loaders: fabric
          game-versions: |
            1.8.9
          dependencies: |
            legacy-fabric-api
            fabric-language-kotlin
          java: 8
          curseforge-id: 626666
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
      - name: Upload jar to CurseForge
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          name: ""
          version: ""
          files-primary: legacy/_1.9.4/build/libs/OKM-*.jar
          files-secondary: ""
          loaders: fabric
          game-versions: |
            1.9.4
          dependencies: |
            legacy-fabric-api
            fabric-language-kotlin
          java: 8
          curseforge-id: 626666
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
      - name: Upload jar to CurseForge
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          name: ""
          version: ""
          files-primary: legacy/_1.10.2/build/libs/OKM-*.jar
          files-secondary: ""
          loaders: fabric
          game-versions: |
            1.10.2
          dependencies: |
            legacy-fabric-api
            fabric-language-kotlin
          java: 8
          curseforge-id: 626666
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
      - name: Upload jar to CurseForge
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          name: ""
          version: ""
          files-primary: legacy/_1.11.2/build/libs/OKM-*.jar
          files-secondary: ""
          loaders: fabric
          game-versions: |
            1.11.2
          dependencies: |
            legacy-fabric-api
            fabric-language-kotlin
          java: 8
          curseforge-id: 626666
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
      - name: Upload jar to CurseForge
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          name: ""
          version: ""
          files-primary: legacy/_1.12.2/build/libs/OKM-*.jar
          files-secondary: ""
          loaders: fabric
          game-versions: |
            1.12.2
          dependencies: |
            legacy-fabric-api
            fabric-language-kotlin
          java: 8
          curseforge-id: 626666
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
      - name: Upload jar to CurseForge
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          name: ""
          version: ""
          files-primary: modern/_1.14.4/build/libs/OKM-*.jar
          files-secondary: ""
          loaders: fabric
          game-versions: |
            1.14.4
          dependencies: |
            fabric-api
            fabric-language-kotlin
          java: 8
          curseforge-id: 626666
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
      - name: Upload jar to CurseForge
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          name: ""
          version: ""
          files-primary: modern/_1.15.2/build/libs/OKM-*.jar
          files-secondary: ""
          loaders: fabric
          game-versions: |
            1.15.2
          dependencies: |
            fabric-api
            fabric-language-kotlin
          java: 8
          curseforge-id: 626666
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
      - name: Upload jar to CurseForge
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          name: ""
          version: ""
          files-primary: modern/_1.16.5/build/libs/OKM-*.jar
          files-secondary: ""
          loaders: fabric
          game-versions: |
            1.16.5
          dependencies: |
            fabric-api
            fabric-language-kotlin
          java: 8
          curseforge-id: 626666
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
      - name: Upload jar to CurseForge
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          name: ""
          version: ""
          files-primary: modern/_1.17.1/build/libs/OKM-*.jar
          files-secondary: ""
          loaders: fabric
          game-versions: |
            1.17.1
          dependencies: |
            fabric-api
            fabric-language-kotlin
          java: 17
          curseforge-id: 626666
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
      - name: Upload jar to CurseForge
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          name: ""
          version: ""
          files-primary: modern/_1.18.2/build/libs/OKM-*.jar
          files-secondary: ""
          loaders: fabric
          game-versions: |
            1.18.2
          dependencies: |
            fabric-api
            fabric-language-kotlin
          java: 17
          curseforge-id: 626666
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
      - name: Upload jar to CurseForge
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          name: ""
          version: ""
          files-primary: modern/_1.19.4/build/libs/OKM-*.jar
          files-secondary: ""
          loaders: fabric
          game-versions: |
            1.19.4
          dependencies: |
            fabric-api
            fabric-language-kotlin
          java: 17
          curseforge-id: 626666
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
      - name: Upload jar to CurseForge
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          name: ""
          version: ""
          files-primary: modern/_1.20.1/build/libs/OKM-*.jar
          files-secondary: ""
          loaders: fabric
          game-versions: |
            1.20.1
          dependencies: |
            fabric-api
            fabric-language-kotlin
          java: 17
          curseforge-id: 626666
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}